version: '3'

services:   

  mysql:
    restart: always
    image: mysql:8.0.11
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'chapter4'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    
volumes:
  mysql_data: